-- ============================================================
--  SUPABASE — copia tudo isto e corre no SQL Editor do Supabase
--  (Dashboard → SQL Editor → New query → Cola → Run)
-- ============================================================

-- 1) Tabela do conteúdo do site (uma única linha, id = 1)
create table if not exists public.site (
  id          int primary key,
  data        jsonb not null default '{}'::jsonb,
  updated_at  timestamptz default now()
);

-- linha inicial
insert into public.site (id, data)
values (1, '{}'::jsonb)
on conflict (id) do nothing;

-- 2) Tabela da galeria (uma linha por foto/vídeo)
create table if not exists public.gallery (
  id          bigint generated by default as identity primary key,
  url         text not null,
  type        text not null default 'image',  -- 'image' | 'video'
  public_id   text,
  created_at  timestamptz default now()
);

-- 3) Realtime
alter publication supabase_realtime add table public.site;
alter publication supabase_realtime add table public.gallery;

-- 4) Row Level Security + políticas públicas
--    (app sem login; qualquer pessoa pode ler/escrever conteúdo e galeria)
alter table public.site    enable row level security;
alter table public.gallery enable row level security;

-- site: ler e atualizar
create policy "site_read"   on public.site   for select using (true);
create policy "site_write"  on public.site   for update using (true) with check (true);
create policy "site_insert" on public.site   for insert with check (true);

-- gallery: ler, inserir, apagar
create policy "gallery_read"   on public.gallery for select using (true);
create policy "gallery_insert" on public.gallery for insert with check (true);
create policy "gallery_delete" on public.gallery for delete using (true);

-- ============================================================
--  Nota de segurança:
--  Estas políticas são abertas (sem login) porque é um app de
--  casamento partilhado por link/QR. Quem souber o link pode
--  contribuir. Se quiseres restringir, fala comigo para
--  acrescentar autenticação.
-- ============================================================
