export const DEFAULT_CONTENT = {
  pt: {
    welcomeTitle: "Bem-vindos",
    welcomeBody:
      "Estamos muito felizes por partilhar este dia convosco. Nesta aplicação vão poder consultar o programa do dia, obter indicações no mapa para a igreja e para a quinta, ver o plano de mesas, receber alertas em tempo real e fazer upload de fotografias e vídeos — cada pessoa, no seu próprio telemóvel, poderá contribuir para a galeria e vê-la em conjunto.",
    accommodationTitle: "Alojamento & Preparação do dia 14",
    accommodationBody:
      "Aqui encontram toda a informação sobre alojamento sugerido nas redondezas e os detalhes da preparação do dia 14 de Agosto: horários de chegada, recomendações de transporte e tudo o que precisam para que o dia corra na perfeição.",
    photoCaption: "Vanessa & Pedro",
  },
  en: {
    welcomeTitle: "Welcome",
    welcomeBody:
      "We are so happy to share this day with you. In this app you'll be able to check the day's schedule, get map directions to the church and the venue, view the seating plan, receive real-time alerts, and upload photos and videos — everyone, on their own phone, can contribute to the gallery and view it together.",
    accommodationTitle: "Accommodation & Getting ready for the 14th",
    accommodationBody:
      "Here you'll find all the information about suggested nearby accommodation and the details for getting ready on August 14th: arrival times, transport recommendations, and everything you need for a perfect day.",
    photoCaption: "Vanessa & Pedro",
  },
};

export const DEFAULT_DATA = {
  schedule: [
    { id: 1, time: "16:00", pt: "Cerimónia na Igreja", en: "Church Ceremony" },
    { id: 2, time: "17:30", pt: "Cocktail de boas-vindas", en: "Welcome cocktail" },
    { id: 3, time: "19:30", pt: "Jantar na Quinta", en: "Dinner at the Venue" },
    { id: 4, time: "23:00", pt: "Festa", en: "Party" },
  ],
  locations: [
    {
      id: 1,
      pt: "Igreja",
      en: "Church",
      address: "Adicionar morada da igreja",
      maps: "https://maps.google.com",
    },
    {
      id: 2,
      pt: "Quinta",
      en: "Venue",
      address: "Adicionar morada da quinta",
      maps: "https://maps.google.com",
    },
  ],
  tables: [
    {
      id: 1,
      name: "Mesa 1 — Mármore",
      guests: [
        { id: 101, name: "Patrícia Palma", age: "", note: "" },
        { id: 102, name: "André Murta", age: "", note: "" },
        { id: 103, name: "Margarida Ramos", age: "", note: "" },
        { id: 104, name: "Cláudia Gaspar", age: "", note: "" },
        { id: 105, name: "João Cunha", age: "", note: "" },
        { id: 106, name: "Francisca Lousada", age: "", note: "" },
        { id: 107, name: "Fábio Ferreira", age: "", note: "" },
        { id: 108, name: "Beatriz Valente", age: "", note: "" },
        { id: 109, name: "Leonardo Mateus", age: "", note: "" },
        { id: 110, name: "Rita Garcia Marques Mateus", age: "", note: "" },
        { id: 111, name: "José Pedro", age: "", note: "Intolerância a marisco" },
        { id: 112, name: "Diogo Oliveira", age: "", note: "" },
      ],
    },
    {
      id: 2,
      name: "Mesa 2",
      guests: [
        { id: 201, name: "Judite Soares", age: "", note: "" },
        { id: 202, name: "Fernando Azevedo", age: "", note: "" },
        { id: 203, name: "Rachel Reis", age: "", note: "" },
        { id: 204, name: "Luis Meira", age: "", note: "" },
        { id: 205, name: "Mara Meira", age: "11", note: "" },
        { id: 206, name: "Diogo Meira", age: "11", note: "" },
        { id: 207, name: "Leandro Soares Reis", age: "", note: "" },
        { id: 208, name: "Tânia Isabel Gomes Frazão Pina Santos", age: "", note: "" },
        { id: 209, name: "Vicente Frazão Reis", age: "5", note: "" },
      ],
    },
    {
      id: 3,
      name: "Mesa 3",
      guests: [
        { id: 301, name: "Aurélio Silva", age: "", note: "" },
        { id: 302, name: "Patrícia Araújo", age: "", note: "" },
        { id: 303, name: "Inês Silva", age: "", note: "" },
        { id: 304, name: "Maria Agripina Coelho", age: "", note: "" },
        { id: 305, name: "Gonçalo Silva", age: "11", note: "Sem sal" },
        { id: 306, name: "Ofélia Gomes", age: "", note: "" },
        { id: 307, name: "José Gomes", age: "", note: "" },
        { id: 308, name: "Hugo Gomes", age: "", note: "" },
      ],
    },
    {
      id: 4,
      name: "Mesa 4",
      guests: [
        { id: 401, name: "Carina Conceição", age: "", note: "" },
        { id: 402, name: "David Andrade", age: "", note: "" },
        { id: 403, name: "Jennifer Cordova", age: "", note: "" },
        { id: 404, name: "Luis Filipe Nunes", age: "", note: "" },
        { id: 405, name: "Susana Isabel Loureiro Morgado", age: "", note: "" },
        { id: 406, name: "Nuno Miguel Marques Pinto", age: "", note: "" },
        { id: 407, name: "Patrícia Oliveira", age: "", note: "" },
        { id: 408, name: "Oscar Rodrigues", age: "", note: "" },
        { id: 409, name: "Tehur Matias", age: "", note: "" },
        { id: 410, name: "Tiago Matias", age: "", note: "" },
      ],
    },
    {
      id: 5,
      name: "Mesa 5",
      guests: [
        { id: 501, name: "Bernardo Clemente", age: "", note: "" },
        { id: 502, name: "Bárbara Teodósio", age: "", note: "" },
        { id: 503, name: "Rémi Gomes", age: "", note: "" },
        { id: 504, name: "Joannie Sommier", age: "", note: "" },
        { id: 505, name: "Lília Gomes", age: "6", note: "" },
        { id: 506, name: "Jonathan Gomes", age: "", note: "" },
        { id: 507, name: "Santiago Gomes", age: "", note: "" },
        { id: 508, name: "Francisca Clemente", age: "", note: "" },
        { id: 509, name: "Miguel Pires", age: "", note: "" },
      ],
    },
    {
      id: 6,
      name: "Mesa 6",
      guests: [
        { id: 601, name: "Joana Raposo", age: "", note: "" },
        { id: 602, name: "Bruno Rosa", age: "", note: "" },
        { id: 603, name: "Carolina Almeida", age: "", note: "" },
        { id: 604, name: "Diogo Almeida", age: "", note: "" },
        { id: 605, name: "Diana Sofia Reis", age: "", note: "" },
        { id: 606, name: "Ivan Filipe Matias Duarte", age: "", note: "" },
        { id: 607, name: "Luciana Fernandes", age: "", note: "Alergia a nozes" },
        { id: 608, name: "Lilia Lopes", age: "", note: "" },
        { id: 609, name: "João Pedro Alves", age: "", note: "" },
        { id: 610, name: "Pedro Fernandes Alves", age: "1", note: "" },
        { id: 611, name: "Luis Miguel Casal dos Santos", age: "", note: "" },
      ],
    },
    {
      id: 7,
      name: "Mesa 7",
      guests: [
        { id: 701, name: "Américo Reis", age: "", note: "" },
        { id: 702, name: "Luisa Moreira", age: "", note: "" },
        { id: 703, name: "Adélia Reis", age: "", note: "" },
        { id: 704, name: "Clara Reis", age: "", note: "" },
        { id: 705, name: "Mariana Moreira", age: "", note: "" },
        { id: 706, name: "Sara Ribeiro", age: "", note: "Intolerância à lactose" },
        { id: 707, name: "Idalina Gomes", age: "", note: "" },
        { id: 708, name: "Diamantino Gomes", age: "", note: "" },
        { id: 709, name: "Paula Clemente", age: "", note: "" },
        { id: 710, name: "Joao Clemente", age: "", note: "" },
      ],
    },
    {
      id: 8,
      name: "Mesa 8",
      guests: [
        { id: 801, name: "Melissa Casteleiro", age: "", note: "" },
        { id: 802, name: "David Sousa", age: "", note: "" },
        { id: 803, name: "Marina Leal", age: "", note: "" },
        { id: 804, name: "Francisco Gabriel Matos da Costa", age: "", note: "" },
        { id: 805, name: "Ana Paula Farias Amaro Antunes", age: "", note: "" },
        { id: 806, name: "Malam Moita Sanhá", age: "", note: "" },
        { id: 807, name: "Inês Rodrigues", age: "", note: "Evitar lactose" },
        { id: 808, name: "João Ribeiro", age: "", note: "" },
        { id: 809, name: "Laura Isabela Brisida Mano Angelino", age: "", note: "" },
        { id: 810, name: "Marco Angelino", age: "", note: "" },
      ],
    },
    {
      id: 9,
      name: "Mesa 9",
      guests: [
        { id: 901, name: "Érica Tavares", age: "", note: "" },
        { id: 902, name: "Kelcio Antunes", age: "", note: "" },
        { id: 903, name: "Kenzo Antunes", age: "", note: "" },
        { id: 904, name: "Rodrigo Augusto", age: "", note: "" },
        { id: 905, name: "Cátia Cid", age: "", note: "" },
        { id: 906, name: "Salvador Cid Jesus", age: "", note: "" },
        { id: 907, name: "Ricardo Silva", age: "", note: "" },
        { id: 908, name: "Tomás Guerreiro", age: "", note: "" },
        { id: 909, name: "Ana Isabel Nunes Dias", age: "", note: "" },
        { id: 910, name: "Carolina Nunes Dias Mateus", age: "", note: "" },
        { id: 911, name: "Isabel Afonso", age: "", note: "" },
      ],
    },
    {
      id: 10,
      name: "Mesa 10",
      guests: [
        { id: 1001, name: "Maria João Rodrigues dos Santos", age: "", note: "" },
        { id: 1002, name: "João Rodrigues Monteiro", age: "", note: "" },
        { id: 1003, name: "Carolina Joia", age: "", note: "" },
        { id: 1004, name: "Cheila Henriques", age: "", note: "" },
        { id: 1005, name: "Inês Pereira", age: "", note: "" },
        { id: 1006, name: "Tatiana Rose", age: "", note: "" },
        { id: 1007, name: "Natacha Nascimento", age: "", note: "" },
        { id: 1008, name: "Raquel Tudella", age: "", note: "" },
      ],
    },
    {
      id: 11,
      name: "Mesa 11",
      guests: [
        { id: 1101, name: "Catarina Cabral", age: "", note: "" },
        { id: 1102, name: "Luís Antunes", age: "", note: "" },
        { id: 1103, name: "Rudi Neves", age: "", note: "" },
        { id: 1104, name: "Cátia Ribeiro", age: "", note: "" },
        { id: 1105, name: "Helena Palma", age: "", note: "" },
        { id: 1106, name: "Luís Palma", age: "", note: "" },
        { id: 1107, name: "Francisca Palma", age: "8", note: "" },
        { id: 1108, name: "Margarida Pinheiro", age: "", note: "" },
        { id: 1109, name: "Rui Ribeiro", age: "", note: "" },
        { id: 1110, name: "Humberto de Carvalho Ferreira", age: "", note: "" },
        { id: 1111, name: "Daniel Ferraz", age: "", note: "" },
      ],
    },
    {
      id: 12,
      name: "Mesa 12",
      guests: [
        { id: 1201, name: "Abdulaziz Alshammari", age: "", note: "" },
        { id: 1202, name: "Petra Gonçalves", age: "", note: "" },
        { id: 1203, name: "Marília Ana Goncalves Leite", age: "", note: "Intolerância a morangos" },
        { id: 1204, name: "Alexandre Seixas", age: "", note: "" },
        { id: 1205, name: "Rita Costa", age: "", note: "" },
        { id: 1206, name: "Sheila Mamad", age: "", note: "" },
        { id: 1207, name: "Ziyaad Mussagi", age: "", note: "" },
        { id: 1208, name: "Raicha Mamad", age: "", note: "Não come porco" },
        { id: 1209, name: "Teresa Castanho", age: "", note: "" },
        { id: 1210, name: "Pedro Cruz", age: "", note: "" },
      ],
    },
    {
      id: 13,
      name: "Mesa 13 — Staff",
      guests: Array.from({ length: 10 }, (_, i) => ({
        id: 1300 + i + 1,
        name: "STAFF",
        age: "",
        note: "",
      })),
    },
    {
      id: 14,
      name: "Mesa 14",
      guests: [
        { id: 1401, name: "João Baptista", age: "", note: "" },
        { id: 1402, name: "Maria Loureiro", age: "", note: "" },
        { id: 1403, name: "Lorena Ramirez", age: "", note: "" },
        { id: 1404, name: "Melania Castro", age: "", note: "" },
        { id: 1405, name: "Ashley Koopman", age: "", note: "" },
        { id: 1406, name: "Cristiano Alba", age: "", note: "" },
        { id: 1407, name: "Jéssica Sousa", age: "", note: "" },
        { id: 1408, name: "Maja Begonja", age: "", note: "" },
        { id: 1409, name: "Alan Bjelic", age: "", note: "" },
      ],
    },
    {
      id: 15,
      name: "Mesa 15 — Staff",
      guests: Array.from({ length: 10 }, (_, i) => ({
        id: 1500 + i + 1,
        name: "STAFF",
        age: "",
        note: "",
      })),
    },
    {
      id: 16,
      name: "Mesa 16 — Staff",
      guests: Array.from({ length: 10 }, (_, i) => ({
        id: 1600 + i + 1,
        name: "STAFF",
        age: "",
        note: "",
      })),
    },
  ],
  alerts: [
    {
      id: 1,
      pt: "Bem-vindos! Fiquem atentos a esta secção para novidades.",
      en: "Welcome! Keep an eye on this section for updates.",
    },
  ],
  accommodation: [
    {
      id: 1,
      ptTitle: "Hotel sugerido",
      enTitle: "Suggested hotel",
      pt: "Adicionar nome, morada e contacto.\nPodes escrever vários parágrafos — cada linha fica separada.",
      en: "Add name, address and contact.\nYou can write several paragraphs — each line stays separate.",
      maps: "",
      photo: "",
    },
  ],
  heroPhoto: "", // dataURL definido no modo admin
};
